[package]
name = "eipscanne-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bilge = "0.2.0"
tokio = { version = "1.42.0", features = ["full"] }
binrw = "0.14.1"
hex-test-macros = { version = "0.1.0", path = "hex_test_macros" }
